# Numpy Array Iterating

#### @jabedkhanjb

Iterating Arrays

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic "for" loop of python.

If we iterate on a 1-D array it will go through each element one by one.

<i>Iterate on the elements of the following 1-D array:</i>

In [1]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x) 

1
2
3


# Iterating 2-D Arrays

In a 2-D array it will go through all the rows.

<i>Iterate on the elements of the following 2-D array:</i>

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]




If we iterate on a n-D array it will go through n-1th dimension one by one.

To return the actual values, the scalars, we have to iterate the arrays in each dimension.

<i>Iterate on each scalar element of the 2-D array:</i>

In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


Here we've used a nested for loop that returns all array elements to the print prompt

# Iterating 3-D Arrays

In a 3-D array it will go through all the 2-D arrays.

<i>Iterate on the elements of the following 3-D array:</i>

In [4]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x) 

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


To return the actual values, the scalars, we have to iterate the arrays in each dimension.

<i>Iterate down to the scalars:</i>

In [5]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for a in arr:
    for b in a:
        for c in b:
            print(c)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()

The function "nditer()" is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

### Iterating on Each Scalar Element

Here in basic "for" loops,  iterating  through each scalar of an array we need  to use <i>n</i> "for" loops which can be difficult to write for arrays with very high dimensionality.

<i>Iterate through the following 3-D array:</i>

In [6]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [7]:
myarr = np.array([[[11,22,33],[44,55,66]],[[77,88,99],[10,100,1000]]])
for x in np.nditer(myarr):
    print(x)

11
22
33
44
55
66
77
88
99
10
100
1000


# Iterating Array With Different Data Types

We can use "op_dtypes" argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in "nditer()" we pass flags=['buffered'].

In [8]:
import numpy as np

arr = np.array([1, 2, 3])
print(f"This is {arr.ndim} dimensational array.")
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x) 

This is 1 dimensational array.
b'1'
b'2'
b'3'


# Iterating With Different Step Size

We can use filtering and followed by iteration.

<i>Iterate through every scalar element of the 2D array skipping 1 element:</i>

In [9]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Dimension number",arr.ndim)
for x in np.nditer(arr[:,::2]):
  print(x) 

Dimension number 2
1
3
5
7


# Enumerated Iteration Using ndenumerate()

Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the "ndenumerate()" method can be used for those usecases.

<i>Enumerate on following 1D arrays elements:</i>

In [10]:
import numpy as np

arr = np.array([1, 2, 3])
print("Dimension Number:",arr.ndim)
myarr = np.array([[[11,22,33],[44,55,66]],[[77,88,99],[10,100,1000]]])
print("Dimension Number:",myarr.ndim)

for idx, x in np.ndenumerate(myarr):
  print(idx, x) 

Dimension Number: 1
Dimension Number: 3
(0, 0, 0) 11
(0, 0, 1) 22
(0, 0, 2) 33
(0, 1, 0) 44
(0, 1, 1) 55
(0, 1, 2) 66
(1, 0, 0) 77
(1, 0, 1) 88
(1, 0, 2) 99
(1, 1, 0) 10
(1, 1, 1) 100
(1, 1, 2) 1000


Here we used 3 dimensional array so the first number represents the first array of the dimension, and the second one represents the dimension of the first array, and the 3rd one represents the array elemtents or index number of second dimension.

<i>Enumerate on following 2D array's elements:</i>

In [11]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x) 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


So in here, the very first number represent the dimension, and the second one represents the array elements index number