# Numpy Array Filter

#### @jabedkhanjb

# Filtering Arrays

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

<i>A boolean index list is a list of booleans corresponding to indexes in the array.</i>

If the value at an index is <b>True</b> that element is contained in the filtered array, if the value at that index is <b>False</b> that element is excluded from the filtered array.

<i>Create an array from the elements on index 0 and 2:</i>

In [1]:
import numpy as np
arr = np.array([41, 42, 43, 44])
x = [True, False, True, True]

newarr = arr[x]
print(newarr)

[41 43 44]


The example above will return <b>[41, 43]</b>, why?

Because the new array contains only the values where the filter array had the value <b>True</b>, in this case, index 0 and 2.

# Creating the Filter Array

In the example above we hard-coded the <b>True</b> and <b>False</b> values, but the common use is to create a filter array based on conditions.

<i><b>create a filter array that will return only values higher than n number</b></i>

In [2]:
import numpy as np

arr = np.array([10, 12, 13, 14, 15, 16, 17, 18, 19, 20])
# create an empty list
filtration = []

# go through each element in arr
for element in arr:
    """if the element is higher than 14, set the value to True,
        Otherwise False. And add them in filtration list using 'append'"""
    if element > 14:
        filtration.append(True)
    else:
        filtration.append(False)
        
newarray = arr[filtration]
        
print(filtration)
print(newarray)

[False, False, False, False, True, True, True, True, True, True]
[15 16 17 18 19 20]


<i><b>Create a filter array that will return only even elements from the original array:</b></i>

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

filtration = []

for numbers in arr:
    if numbers % 2 == 0: # even
        filtration.append(True)
    else: # false
        filtration.append(False)
        
newarray = arr[filtration]

print(filtration)
print(newarray)

[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


# Creating Filter Directly From Array

The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

<i><b>Create a filter array that will return only values higher than n number:</b></i>

In [9]:
import numpy as np

arr = np.array([50, 51, 52, 53, 54, 55])

filtration = arr > 52

newarr = arr[filtration]

print(filtration)
print(newarr)

[False False False  True  True  True]
[53 54 55]


<i><b>Create a filter array that will return only even or odd number as per instruction</b></i>

In [16]:
import numpy as np

arr = np.array([5,6,2,7,7,3,6,4,5,3,8,2,8,4,7,4,6,6,4,7])

filtration = arr % 2 == 0 # if 0, it would be even. if 1, then odd

newarray = arr[filtration]

print(filtration)
print(newarray)

[False  True  True False False False  True  True False False  True  True
  True  True False  True  True  True  True False]
[6 2 6 4 8 2 8 4 4 6 6 4]


# Numpy Array Chapter End. 