## Create  a Numpy ndarray Object


#### @jabedkhanjb

In [2]:
import numpy as np

arr = np.array([1, 3, 5, 7, 9])
print(arr)
print(type(arr))

[1 3 5 7 9]
<class 'numpy.ndarray'>


type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.

### To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [7]:
myarray = (9, 7, 5, 3, 1)


print(np.array(myarray))

[9 7 5 3 1]


## Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.


# 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

<i>Create a 0-D array with value n number</i>

In [5]:
import numpy as np
arr = np.array(42)
print(arr)

42


# 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

<i>Create a 1-D array containing the values 1,2,3,4,5:</i>

In [9]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


# 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called <b>numpy.mat</b>

<i>Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:</i>

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr) 

[[1 2 3]
 [4 5 6]]


# 3-D Arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

<i>Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:</i>

In [15]:
myarray = [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]
x = np.array(myarray)
print(x)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions?

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

<i>Check how many dimensions the arrays have:</i>

In [21]:
a = np.array(42) # O-D Dimension
b = np.array([1, 2, 3, 4, 5]) # 1-D Dimension
c = np.array([[1, 2, 3], [4, 5, 6]]) # 2-D Dimension
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # 3-D Dimension

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(type(d))

0
1
2
3
<class 'numpy.ndarray'>


# Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

<i>Create an array with 5 dimensions and verify that it has 5 dimensions:</i>

In [25]:
myarray = [1, 2, 3, 4]

highD = np.array(myarray, ndmin = 5)
print(highD)
print(f"Number of dimensions: {highD.ndim}")

[[[[[1 2 3 4]]]]]
Number of dimensions: 5
