# Numpy Data Types

#### @jabedkhanjb


Data Types in Python

By default Python have these data types:

    strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
    integer - used to represent integer numbers. e.g. -1, -2, -3 or 1, 2, 3
    float - used to represent real numbers. e.g. 1.2, 42.42
    boolean - used to represent True or False.
    complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )


# Checking the Data Type of an Array

The NumPy array object has a property called dtype that returns the data type of the array:

<i>Get the data type of an array object:</i>

In [4]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [8]:
arr = np.array(['iPhone', 'MacBook', 'Android', 'Windows'])
print(arr[::1])
print(arr.dtype)

['iPhone' 'MacBook' 'Android' 'Windows']
<U7


# Creating Arrays With a Defined Data Type

We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [11]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [13]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# What if a Value Can Not Be Converted?

If a type is given in which elements can't be casted then NumPy will raise a ValueError.

ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.


<i>A non integer string like 'a' can not be converted to integer (will raise an error):</i>

In [14]:
# Precaution: This code has ValueError

import numpy as np

arr = np.array(['a', '2', '3'], dtype='i') 

ValueError: invalid literal for int() with base 10: 'a'

# Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

<i>Change data type from float to integer by using 'i' as parameter value:</i>


In [9]:
arr = np.array([1.1, 2.1, 3.1]) 

newarr = arr.astype('i')

print(arr)
print(arr.dtype)
print(newarr)
print(newarr.dtype) 

[1.1 2.1 3.1]
float64
[1 2 3]
int32


Change data type from float to integer by using int as parameter value:

In [10]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype("int")

print(newarr)
print(newarr.dtype) 

[1 2 3]
int32


Change data type from integer to float by using f and float as parameter value:

In [11]:
arr = np.array([1, 5, 6, 9, 12, 75])

print(arr)
print(arr.dtype)
newarr = arr.astype("f")
print("Using f parameter:", newarr.dtype)

secarr = arr.astype("float")
print("Using float parameter:", secarr.dtype)

[ 1  5  6  9 12 75]
int32
Using f parameter: float32
Using float parameter: float64


so the difference i can see above is that when we use f for float parameter to convert our integer array, it shows the dtype of this array as float32, and on either if we replace f to float as a parameter of float to convert integer into float it shows the dtype as float64

<i>Change data type from integer to boolean:</i>

In [15]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype) 

[ True False  True]
bool


Okay now we will change the array value into float and let's see what gonna happen in boolean method.

In [17]:
arr = np.array([1.01, 0.1, 3.2, 0.9, 0])

newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True  True  True  True False]
bool


### Note: 
In boolean 0 means False and 1 means True. and in our float array we took some array numbers as 0.1, 0.9 and from the mathematical view these are not exactly 0
so, 0.1 or 0.9 these are completely more than 0 and which is not supposed to be True and that happened in our program execution. it tooks 0 parameter as a False boolean. 

## github.com/jabedkhanjb