# Numpy Array Slicing

#### @jabedkhanjb

# Slicing arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

<i>Slice elements from index 1 to index 5 from the following array:</i>

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("Slicing: ", arr[1:5])

Slicing:  [2 3 4 5]


<i>Slice elements from n index to the end of the array:</i>

now we will print the value from start index to the end of the array only by passing start index value.
here we ain't calling import numpy or array constant each time

In [6]:
print("Start Index to the end of the array:", arr[4:])

Start Index to the end of the array: [5 6 7]


<i>Slice elements from the beginning to the n index (not included):</i>

In [8]:
print("from the beginning to the n index:", arr[:2])

from the beginning to the n index: [1 2]


# Negative Slicing

Use the minus operator to refer to an index from the end:


<i>Slice from the index 3 from the end to index 1 from the end:</i>

In [12]:
print(arr[-4:-1])

[4 5 6]


In [18]:
import numpy as np

myarray = np.array([75, 89, 48 , 62, 15, 34, 25, 96, 40])
print("Specify Start & End index:", myarray[2:6])
print("Specify Start index:", myarray[4:])
print("Specify End index:", myarray[:6])
print("Negative indexing:", myarray[-8:-2])


Specify Start & End index: [48 62 15 34]
Specify Start index: [15 34 25 96 40]
Specify End index: [75 89 48 62 15 34]
Negative indexing: [89 48 62 15 34 25]


# STEP

Use the step value to determine the step of the slicing:

<i>Return every other element from index 1 to index 5:</i>

In [26]:
myarray = np.array([75, 89, 48 , 62, 15, 34, 25, 96, 40])
print(myarray[1:8:3])

[89 15 96]


<b>Note:</b> here 3 represents that the number of index between 1 to 8 will print each after 3 index numbers consecutively

<i>Return every other element from the entire array:</i>

In [27]:
print(myarray[::2])
print(myarray[::3])
print(myarray[::5])

[75 48 15 25 40]
[75 62 25]
[75 34]


# Slicing 2-D Arrays

<i>From the second element, slice elements from index 1 to index 4 (not included):</i>



In [36]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) 
print(arr[0, :4]) 
print(arr[0, 3:]) 
print(arr[1, -4:-2]) 


[7 8 9]
[1 2 3 4]
[4 5]
[7 8]


<i>From both elements, return n index:</i>

In [42]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 4]) 

[ 5 10]
