# Numpy Sorting Arrays

#### @jabedkhanjb

# Sorting Arrays

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called <b>sort()</b>, that will sort a specified array.

In [1]:
import numpy as np
arr = np.array([5,3,6,2,6,7,2,7,1,9,0,6,4])
print(np.sort(arr))

[0 1 2 2 3 4 5 6 6 6 7 7 9]


<b>Note:</b> This method returns a copy of the array, leaving the original array unchanged

<i>You can also sort arrays of strings, or any other data type:</i>

In [2]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple', 'anatomy'])

print(np.sort(arr)) 

['anatomy' 'apple' 'banana' 'cherry']


<i>Sort a boolean array:</i>

In [3]:
import numpy as np

arr = np.array([True, False, False, True, False, True])

print(np.sort(arr)) 

[False False False  True  True  True]


# Sorting a 2-D Array

If you use the sort() method on a 2-D array, both arrays will be sorted:

<i><b>Sort a 2-D array:</b></i>

In [4]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr)) 

[[2 3 4]
 [0 1 5]]
