# Numpy Array Searching


#### @jabedkhanjb

# Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the <b>where()</b> method.

<i><b>Find the indexes where the value is n:</b></i>

In [2]:
import numpy as np
myarray = np.array([1,2,3,4,5,6,7,8,9,5,7,9,5,7])
newarray = np.where(myarray == 5)
print(newarray)

(array([ 4,  9, 12], dtype=int64),)


Which means that the value n is present at index a, b, and c.

<i><b>Find the indexes where the values are odd:</b></i>

In [8]:
import numpy as np
# print(len(nmbrarr))
myarray = np.array([2, 5, 8, 11])
evenodd = np.where(myarray % 2 == 1) # for odd
print(evenodd)



(array([1, 3], dtype=int64),)


# Search Sorted

There is a method called <b>searchsorted()</b> which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

<i><b>The searchsorted() method is assumed to be used on sorted arrays.</b></i>


In [46]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
x = np.searchsorted(arr, 9)
print(f"Number of length: {len(arr)}")
print(x)

Number of length: 9
8


Example explained: The number n should be inserted on index n to remain the sort order.

The method starts the search from the left and returns the first index where the number n is no longer larger than the next value.

# Search From the Right Side

<i>By default the left most index is returned, but we can give <b>side='right'</b> to return the right most index instead.</i>

In [50]:
import numpy as np
arr =  np.array([4,6,8,9])
x = np.searchsorted(arr, 9, side="right")
print(x)

4


Example explained: The number n should be inserted on index n to remain the sort order.

The method starts the search from the right and returns the first index where the number n is no longer less than the next value.

# Multiple Values

To search for more than one value, use an array with the specified values.

<i><b>Find the indexes where the values 2, 4, and 6 should be inserted:</b></i>

In [64]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x) 

[1 2 3]


The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.