# Numpy Array Split

#### @jabedkhanjb

# Splitting NumPy Arrays

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use <b>array_split()</b> for splitting arrays, we pass it the array we want to split and the number of splits.

<i>Split the array in 3 parts:</i>

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr) 

[array([1, 2]), array([3, 4]), array([5, 6])]




<b>Note:</b> The return value is an array containing three arrays.


If the array has less elements than required, it will adjust from the end accordingly.

<i>Split the array in 4 parts:</i>

In [11]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


<b>Note:</b> We also have the method <b>split()</b> available but it will not adjust the elements when elements are less in source array for splitting like in example above, <b>array_split()</b> worked properly but <b>split()</b> would fail.

# Split Into Arrays

The return value of the <b>array_split()</b> method is an array containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:
Example

<i>Access the splitted arrays:</i>

In [13]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

newarr = np.array_split(arr, 4)
print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])

[1 2]
[3 4]
[5 6]
[7 8]


# Splitting 2-D Arrays

Use the same syntax when splitting 2-D arrays.

Use the <b>array_split()</b> method, pass in the array you want to split and the number of splits you want to do.

In [25]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]


The example above returns three 2-D arrays.

In addition, you can specify which axis you want to do the split around.

The example below also returns three 2-D arrays, but they are split along the row (axis=1).

<i>Split the 2-D array into three 2-D arrays along rows.</i>

In [27]:
arr2 = np.array([[13,14,15], [16,17,18]])
myarray = np.concatenate((arr, arr2))
print(myarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


so in this code above, we used array joining function call concatenate to add one more array with out previous array.

In [31]:
newarray = np.array_split(myarray, 3, axis = 1)
print(newarray)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


An alternate solution is using hsplit() opposite of hstack()

<i>Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.</i>

In [34]:
import numpy as np

arr = np.array([myarray])
print(myarray)
newhsplit = np.hsplit(myarray, 3)
print(newhsplit)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().