# Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

<i>Get the first element from the following array:</i>

In [3]:
import numpy as np

value = [1, 2, 3, 4, 5]

x = np.array(value)
print(x[2])

3


### My Customizations on Access array elements


In [4]:
import numpy as np

value = [1, 2, 3, 4, 5]

x = np.array(value)
index = int(input("Insert an index number to fetch the array element: "))
print(f"Index number {index} has {x[index]}")


Insert an index number to fetch the array element: 2
Index number 2 has 3


<i>Get third and fourth elements from the following array and add them.</i>

In [5]:
print(x[2] + x[3])

7


# Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [15]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("3rd element of 2nd row:", arr[1,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3rd element of 2nd row: 8


In [16]:
myarr = np.array([[1, 2, 3], [7, 8, 9]])
print(myarr)
print("2nd element of 1st row:",myarr[0, 1])

[[1 2 3]
 [7 8 9]]
2nd element of 1st row: 2


# Access 3-D Arrays

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

<i>Access the third element of the second array of the first array:</i>

In [ ]:
arr = np. 