# Numpu Array Reshaping

#### @jabedkhanjb

# Reshaping arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

# Reshape From 1-D to 2-D

<i>Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:</i>

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Reshape From 1-D to 3-D

<i>Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:</i>

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr) 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Okay now we are gonna convert this again in a different way that the outermost dimension will have 2 arrays that contains 2 arrays, each with 3 elements.

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 2, 3)

print(newarr) 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


So, as we can see here that the arrays is a 3D array where its outermost dimention have 

Okay now we are gonna convert this once again in a different way that the outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements.

In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 2, 2)

print(newarr) 

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


# Can We Reshape Into any Shape?

Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

<i>Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):</i>

In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr) 

ValueError: cannot reshape array of size 8 into shape (3,3)

# Returns Copy or View?

<i>Check if the returned array is a copy or a view:</i>

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4))
print("""\nNow we can see the original array by using base term 
which represents view attribute of numpy.\n""")
print(arr.reshape(2, 4).base)

[[1 2 3 4]
 [5 6 7 8]]

Now we will see the original array by using base term 
which represents view attribute of numpy.

[1 2 3 4 5 6 7 8]


The example above returns the original array, so it is a view.

# Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

<i>Convert 1D array with 8 elements to 3D array with 2x2 elements:</i>

In [38]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2,2,-1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use "reshape(-1)" to do this

<i>Convert the array into a 1D array:</i>

In [46]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)
print(arr,"\n")
print(newarr) 

[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 6]


In reshape, using more than -1 for instance -2, -3 or even -10 doesn't change the meaning of purpose of reshape in here. Recommended to use -1

#### Note: 
There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

#### Mahfuz Islam Khan Jabed
<i>@jabedkhanjb</i>