# Numpy Array Copy vs View

# The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

# COPY:

<i>Make a copy, change the original array, and display both arrays:</i>

In [16]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
myarr = arr.copy()
arr[9] = 1

print(myarr)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7 8 9 1]


In this code above, we copied the main array(arr) into a new array(myarr)
but we changed the index number 9 which has 10, turned into 1 and we printed them later.

<i>The copy SHOULD NOT be affected by the changes made to the original array.</i>

# VIEW:

<i>Make a view, change the original array, and display both arrays:</i>

In [12]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
myarr = arr.view()
arr[0] = 42

print(myarr)
print(arr) 

[42  2  3  4  5  6  7  8  9 10]
[42  2  3  4  5  6  7  8  9 10]


So in this code above, the term "view" changed the original array and displayed both arrays.

<i>The view SHOULD be affected by the changes made to the original array.</i>

# Check if Array Owns its Data

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute "base" that returns "None" if the array owns the data.

Otherwise, the "base" attribute refers to the original object. 

<i>Print the value of the base attribute to check if an array owns its data or not:</i>

In [14]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[ 1  2  3  4  5  6  7  8  9 10]
